package by.epam.pavelshakhlovich.onlinepharmacy.command.util;

/**
 * Contains names of all possible http parameters
 */
public final class Parameter {
    public static final String ADDRESS = "address";
    public static final String AMOUNT = "amount";
    public static final String BY_PRESCRIPTION = "by_prescription";
    public static final String CART_ITEMS = "cart_items";
    public static final String CUSTOMER_ID = "customer_id";
    public static final String COMMAND = "command";
    public static final String COUNTRIES = "countries";
    public static final String COUNTRY = "country";
    public static final String COUNTRY_ID = "country_id";
    public static final String COMPANIES = "companies";
    public static final String COMPANY = "company";
    public static final String DATE = "date";
    public static final String DOCTOR_ID = "doctor_id";
    public static final String DOSAGE= "dosage";
    public static final String DOSAGES= "dosages";
    public static final String DOSAGE_ID= "dosage_id";
    public static final String DESCRIPTION = "description";
    public static final String DRUG_ID= "drug_id";
    public static final String EMAIL = "email";
    public static final String ERROR_MESSAGE = "error_message";
    public static final String ERROR_MESSAGE_DELETE = "error_message_delete";
    public static final String ERROR_COUNTRY_MESSAGE = "error_country_message";
    public static final String ERROR_DOSAGE_MESSAGE = "error_dosage_message";
    public static final String FIRST_NAME = "first_name";
    public static final String ID = "id";
    public static final String ITEM = "item";
    public static final String ITEM_ID = "item_id";
    public static final String ITEMS = "items";
    public static final String LABEL = "label";
    public static final String LAST_NAME = "last_name";
    public static final String LIMIT = "limit";
    public static final String LOCALE = "locale";
    public static final String LOGIN = "login";
    public static final String MANUFACTURER_ID = "manufacturer_id";
    public static final String MANUFACTURER_NAME = "manufacturer_name";
    public static final String NAME = "name";
    public static final String NUMBER_OF_ITEMS = "number_of_items";
    public static final String NUMBER_OF_ORDERS = "number_of_orders";
    public static final String NUMBER_OF_USERS = "number_of_users";
    public static final String OLD_QUANTITY = "old_quantity";
    public static final String ORDER = "order";
    public static final String ORDER_EVENTS = "order_events";
    public static final String ORDER_OWNER = "order_owner";
    public static final String ORDERS = "orders";
    public static final String ORDER_ID = "order_id";
    public static final String CHANGE_QUANTITY = "change_quantity";
    public static final String PAGE_NUMBER = "page_number";
    public static final String PASSWORD = "password";
    public static final String PASSWORD_MD5 = "password_md5";
    public static final String PRESCRIPTIONS = "prescriptions";
    public static final String PRICE = "price";
    public static final String QUANTITY = "quantity";
    public static final String REFERER = "referer";
    public static final String ROLE = "role";
    public static final String SALT = "salt";
    public static final String SEARCH = "search";
    public static final String SHOPPING_CART = "shopping_cart";
    public static final String SHOPPING_CARD_DESERIALIZATION_DONE = "shopping_card_deserialization_done";
    public static final String STATUS = "status";
    public static final String STATUS_LIST = "status_list";
    public static final String SUCCESS_MESSAGE = "success_message";
    public static final String SUCCESS_MESSAGE_DELETE= "success_delete_message";
    public static final String SUCCESS_COUNTRY_MESSAGE = "success_country_message";
    public static final String SUCCESS_DOSAGE_MESSAGE = "success_dosage_message";
    public static final String TOTAL_AMOUNT = "total_amount";
    public static final String USER = "user";
    public static final String USERS = "users";
    public static final String USER_ID = "user_id";
    public static final String USER_NAME = "user_name";
    public static final String USER_ROLE = "user_role";
    public static final String VALID_UNTIL = "valid_until";
    public static final String VOLUME = "volume";
    public static final String VOLUME_TYPE = "volume_type";
    public static final String VOLUME_TYPES = "volume_types";
    public static final String WEBSITE = "website" ;

}
